package _27135.q1;

import java.time.LocalDate;

public final class StockReport extends Inventory {
    private LocalDate reportDate;
    private String remarks;

    public StockReport(int id, LocalDate createdDate, LocalDate updatedDate,
                       String warehouseName, String location, String contactNumber,
                       String categoryName, String categoryCode,
                       String supplierName, String supplierEmail, String supplierPhone,
                       String productName, double unitPrice, int stockLimit,
                       int quantityAvailable, int reorderLevel,
                       LocalDate purchaseDate, int purchasedQuantity, String purchaseSupplierName,
                       LocalDate saleDate, int soldQuantity, String customerName,
                       int totalItems, double stockValue,
                       LocalDate reportDate, String remarks) {
        super(id, createdDate, updatedDate, warehouseName, location, contactNumber,
                categoryName, categoryCode, supplierName, supplierEmail, supplierPhone,
                productName, unitPrice, stockLimit, quantityAvailable, reorderLevel,
                purchaseDate, purchasedQuantity, purchaseSupplierName,
                saleDate, soldQuantity, customerName, totalItems, stockValue);
        this.reportDate = reportDate;
        this.remarks = remarks;
    }

    public LocalDate getReportDate() {
        return reportDate;
    }

    public void setReportDate(LocalDate reportDate) {
        this.reportDate = reportDate;
    }

    public String getRemarks() {
        return remarks;
    }

    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    public void generateReport() {
        System.out.println("\n" + "=".repeat(80));
        System.out.println("27135 - STOCK MANAGEMENT REPORT");
        System.out.println("=".repeat(80));
        System.out.println("Report Date: " + reportDate);
        System.out.println("Generated By: Student ID 27135");
        System.out.println("-".repeat(80));

        System.out.println("\n>>> WAREHOUSE INFORMATION <<<");
        System.out.println("Warehouse Name: " + getWarehouseName());
        System.out.println("Location: " + getLocation());
        System.out.println("Contact Number: " + getContactNumber());

        System.out.println("\n>>> CATEGORY INFORMATION <<<");
        System.out.println("Category Name: " + getCategoryName());
        System.out.println("Category Code: " + getCategoryCode());

        System.out.println("\n>>> SUPPLIER INFORMATION <<<");
        System.out.println("Supplier Name: " + getSupplierName());
        System.out.println("Supplier Email: " + getSupplierEmail());
        System.out.println("Supplier Phone: " + getSupplierPhone());

        System.out.println("\n>>> PRODUCT INFORMATION <<<");
        System.out.println("Product Name: " + getProductName());
        System.out.println("Unit Price: RWF " + getUnitPrice());
        System.out.println("Stock Limit: " + getStockLimit());

        System.out.println("\n>>> STOCK DETAILS <<<");
        System.out.println("Quantity Available: " + getQuantityAvailable());
        System.out.println("Reorder Level: " + getReorderLevel());

        System.out.println("\n>>> PURCHASE INFORMATION <<<");
        System.out.println("Purchase Date: " + getPurchaseDate());
        System.out.println("Purchased Quantity: " + getPurchasedQuantity());
        System.out.println("Purchase Supplier: " + getPurchaseSupplierName());

        System.out.println("\n>>> SALES INFORMATION <<<");
        System.out.println("Sale Date: " + getSaleDate());
        System.out.println("Sold Quantity: " + getSoldQuantity());
        System.out.println("Customer Name: " + getCustomerName());

        System.out.println("\n>>> INVENTORY SUMMARY <<<");
        System.out.println("Total Items in Stock: " + getTotalItems());
        System.out.println("Total Stock Value: RWF " + getStockValue());

        System.out.println("\n>>> REPORT REMARKS <<<");
        System.out.println(remarks);

        System.out.println("\n" + "=".repeat(80));
        System.out.println("27135 - END OF REPORT");
        System.out.println("=".repeat(80));
    }

    @Override
    public String toString() {
        return "27135 - StockReport{" +
                "reportDate=" + reportDate +
                ", remarks='" + remarks + '\'' +
                ", totalItems=" + getTotalItems() +
                ", stockValue=" + getStockValue() +
                '}';
    }
}